# Generated by Django 5.0.4 on 2024-05-09 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_general_shipping_alter_coupon_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 19, 12, 54, 11, 7423, tzinfo=datetime.timezone.utc)),
        ),
    ]
