# Generated by Django 5.0.4 on 2024-05-09 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_alter_coupon_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 19, 13, 5, 52, 288511, tzinfo=datetime.timezone.utc)),
        ),
    ]
