# Generated by Django 5.0.4 on 2024-05-11 05:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_alter_coupon_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedCupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('user', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 21, 5, 28, 5, 771457, tzinfo=datetime.timezone.utc)),
        ),
    ]
