# Generated by Django 5.0.4 on 2024-04-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_alter_featurevalue_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfeature',
            name='feature_value',
            field=models.ManyToManyField(blank=True, related_name='product_features', to='features.featurevalue'),
        ),
    ]
