# Generated by Django 5.0.4 on 2024-04-30 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_alter_productfeature_feature_value'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfeature',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_features', to='products.product'),
        ),
    ]
